version: '3.4'

services:
  pricelists:
    image: pricelists
    build:
      context: .
    environment:
      PRICELIST_DB_URL: host=database port=5435 user=sa dbname=/tmp/pricelist sslmode=disable
      BRANDS_DB_URL: host=database port=5435 user=sa dbname=/tmp/brands sslmode=disable
    ports:
      - 8080:80

  database:
    image: h2:1.0
    build:
      context: ./database
    ports:
    - 8082:8082
    - 9092:9092
    - 5435:5435